### ISSUE TITLE
I cannot make this work on another email & google api account

### ISSUE THREAD

**Issue by RandyT97** [warren1215/E-Z-Notes#3]
It only works on mine, relevant links:

https://developers.google.com/picker/docs/

https://developers.google.com/apps-script/guides/web

The issue looks to be due to misconfiguration of credentials (should all be config.js).

EDIT: I've made a README and I believe it works, if someone could test it out before merging it, that would be great.
https://github.com/jawyuhz/E-Z-Notes/blob/master/README.md

**Comment by warren1215** [comment]
Got it working, but still need someone to look at pull request #5 and follow the README.
